# I like my prompt on a single line
add_newline = false

# Only show commands duration if longer than 10 seconds
[cmd_duration]
min_time = 10000

[jobs]
disabled = true

[kubernetes]
disabled = false

[gcloud]
disabled = true