# Only show commands duration if longer than 10 seconds
[cmd_duration]
min_time = 10000

[container]
style="green"

[gcloud]
disabled = true

[jobs]
disabled = true

[kubernetes]
disabled = false

[os]
disabled = false

[sudo]
disabled = false